### ISSUE TITLE
Question on Sim3 PoseGraph Optimization with Ceres 

### ISSUE THREAD

**Issue by ferreram** [darglein/saiga#19]
Hi there,

Impressive work!  As I have seen that you have been dealing with PGO using ceres along with sophus based Sim3, I was wondering if you had any tips to share here?  I have seen that you have turned to the use of DSim3 for PGO, is the use of such decoupled representation enough to make it compliant with ceres's way of computing gradient?  Or is it mandatory to modify the gradient computation in ceres to keep it on the lie algebra space and avoid huge gradients?

Thanks!

**Comment by darglein** [comment]
Hello!

My Ceres PGO solver uses DSim3 AND local parametrization see here https://github.com/darglein/saiga/blob/master/src/saiga/vision/ceres/local_parameterization_se3.h

In my experiments that works quite well with Ceres Autodiff so it's very convenient for implementation. However for Snake-SLAM I use a direct implementation without Ceres which you can find here https://github.com/darglein/saiga/blob/master/src/saiga/vision/recursive/PGOSim3Recursive.cpp

**Comment by ferreram** [comment]
Alright thanks!
