### ISSUE TITLE
compilation error with bullet installed

### ISSUE THREAD

**Issue by ipatix** [darglein/saiga#6]
OS: Debian Buster (x86_64)
Version: 1af9c420987f5b996d5b713378d8137c521fd18a

If libbullet-dev is installed compilation will fail:

```
[ 83%] Building CXX object samples/opengl/simpleBullet/CMakeFiles/opengl_simpleBullet.dir/bulletDebugDrawer.cpp.o
/tmp/saiga/samples/opengl/simpleBullet/bulletDebugDrawer.cpp: In constructor ‘Saiga::GLDebugDrawer::GLDebugDrawer()’:
/tmp/saiga/samples/opengl/simpleBullet/bulletDebugDrawer.cpp:13:32: error: ‘instance’ is not a member of ‘Saiga::ShaderLoader’
     lineShader = ShaderLoader::instance()->load<MVPShader>("geometry/deferred_mvp_model_forward.glsl");
                                ^~~~~~~~
/tmp/saiga/samples/opengl/simpleBullet/bulletDebugDrawer.cpp:13:58: error: expected primary-expression before ‘>’ token
     lineShader = ShaderLoader::instance()->load<MVPShader>("geometry/deferred_mvp_model_forward.glsl");
```

Removing bullet or forcefully disabling it in the cmake files will make it work again (which I guess isn't the most appropriate long term solution).

**Comment by darglein** [comment]
This issue has already been fixed in the experimental branch. Commit https://github.com/darglein/saiga/commit/cdc0596857e46c903af9db6221090e86ba348ffd

**Comment by ipatix** [comment]
As far as I can tell the latest changes are now on the master branch as well.

Thanks :)
