### ISSUE TITLE
Vulkan support broken

### ISSUE THREAD

**Issue by ipatix** [darglein/saiga#7]
Compiling saiga with Vulkan support and then linking a program against saiga raises the following errors:

1st: cmake error:
  Target "agphys" links to target "Vulkan::Vulkan" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

2nd: linker error:
/usr/bin/ld: cannot find -lVulkan::Vulkan

version used: a42470a7a2d5959d335265ac69d253e411eaebe7

A current workaround is to disable Vulkan when compiling saiga.

**Comment by darglein** [comment]
I could not recreate this problem on my system. While looking for a problem I did some cleanup on the install code. Can you please test it again with 5c1253a8509a20b956f9a4560db96e2a94e05f08 on the experimental branch?

**Comment by ipatix** [comment]
Unfortunately the problem is still present.

These are the generated cmake files after running `make install`:

[saigacmake.tar.gz](https://github.com/darglein/saiga/files/3848075/saigacmake.tar.gz)

Here is the build config, in case that helps:

[saigaheaders.tar.gz](https://github.com/darglein/saiga/files/3848083/saigaheaders.tar.gz)

What's suspicious is in the generated "SaigaTargets.cmake" line 65 where it says "Vulkan::Vulkan". That obviously is no valid library name to link against. I have to idea what's causing it, though.

**Comment by darglein** [comment]
It should be fixed now in 01f19f8cd7b7fc71a026873b8dacf365b7bde518.

The problem was that saiga_cuda had a cmake dependency to saiga_vulkan even though it didn't use it.

**Comment by ipatix** [comment]
Works, thank you very much!
